# Generated by Django 3.2.3 on 2022-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
